include: package:lint/analysis_options.yaml
# package: flutter_lints/flutter.yaml

linter:
  rules:
    file_names: false
    curly_braces_in_flow_control_structures: false
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    prefer_single_quotes: true
    avoid_void_async: false
    sized_box_for_whitespace: false
    prefer_interpolation_to_compose_strings: false
    avoid_print: false
    # always_specify_types: true
    # const_initialized_with_non_constant_value: false
    # import_of_legacy_library_into_null_safe: false
    avoid_positional_boolean_parameters: false
    use_string_buffers: false
    use_build_context_synchronously: false
    depend_on_referenced_packages: false
    join_return_with_assignment: false

analyzer:
  # errors:
  #   invalid_annotation_target: ignore

  exclude:
    - zzzz/*
    - lib/model/*.g.dart
    - lib/model/*.freezed.dart
    - lib/cubit/*.freezed.dart
    - lib/cubit/**/*.freezed.dart
