name: sats
description: Advanced Bitcoin Wallet
publish_to: 'none' 
version: 0.2.7

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter  

  get_it: ^6.0.0
  bloc: ^7.1.0
  flutter_bloc: ^7.2.0
  equatable: ^2.0.3
  provider: ^6.0.0
  #hive: ^2.0.2
  flutter_secure_storage: ^4.2.1
  path_provider: ^2.0.1
  retry: ^3.1.0
  dio: ^4.0.0
  pin_input_text_field: ^4.0.0
  # flutter_statusbarcolor: ^0.2.3
  animations: ^2.0.0
  url_launcher: ^6.0.3
  open_mail_app: ^0.1.1
  share: ^2.0.1
  qr_flutter: ^4.0.0
  petitparser: ^4.1.0
  intl: ^0.17.0
  
  # firebase_auth: ^1.4.1
  firebase_dynamic_links: ^2.0.6
  firebase_core: ^1.3.0

  #sentry_flutter: ^4.1.0-nullsafety.1
  oktoast: ^3.0.0
  animate_do: ^2.0.0
  # flutter_vibrate: ^1.1.0

  google_fonts: ^2.0.0
  freezed_annotation: ^0.14.3
  json_serializable: ^5.0.0
  connectivity: ^3.0.3
  flutter_blue: ^0.8.0
  flutter_barcode_scanner: ^2.0.0

  bitcoin:
    path: packages/bitcoin


dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  #integration_test:
  #  sdk: flutter

  #test: any #^1.15.7
  #bloc_test: any #^8.0.0
  #mockito: #^5.0.0

  freezed: ^0.14.5
  build_runner: ^2.0.5

  
#dependency_overrides:
#  crypto: any #^2.0.3
#  build: any #^2.0.1
#  intl: ^0.17.0-nullsafety.2


flutter:
  uses-material-design: true