[package]
name = "ditto"
version = "0.5.1"
authors = ["VM <vishalmenon.92@gmail.com>, MJ <jmorteza@hotmail.com>"]
edition = "2018"

[lib]
name = "ditto"
crate-type = ["staticlib", "cdylib"]

[dependencies]
serde = "1.0.126"
serde_json = "1.0.64"
serde_derive = "1.0.0"
bip39 = "1.0.1"
rand = "0.6.0"
bitcoin = "0.26.0"
secp256k1 = {version = "0.20.1", features = ["rand"]}
base64 = "0.13.0"
bdk = {version = "0.9.0", features = ["compiler"]}
