include: package:lint/analysis_options.yaml
# package: flutter_lints/flutter.yaml

linter:
  rules:
    file_names: false
    curly_braces_in_flow_control_structures: false
    sort_constructors_first: true
    prefer_single_quotes: true
    # always_specify_types: true
    # const_initialized_with_non_constant_value: false
    # import_of_legacy_library_into_null_safe: false



analyzer:
  enable-experiment:
    - non-nullable
  errors:
    invalid_annotation_target: ignore